name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - giselle2.5
  workflow_dispatch:

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test

  supabase-migrations:
    name: Supabase Migrations
    needs: lint-and-test
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'
      - name: Install Supabase CLI
        run: npm install -g @supabase/cli
      - name: Run migrations
        run: npx supabase db push --project-ref ${{ secrets.SUPABASE_PROJECT_REF }} --schema public
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

  deploy-to-vercel:
    name: Deploy to Vercel
    needs: [lint-and-test, supabase-migrations]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Generate barrel files
        run: yarn generate:barrels
      - name: Build
        run: yarn build:all
        env:
          # Database Configuration
          PG_DATABASE_URL: ${{ secrets.PG_DATABASE_URL }}
          
          # Authentication
          ENCRYPTION_SECRET: ${{ secrets.ENCRYPTION_SECRET }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          LOGIN_TOKEN_SECRET: ${{ secrets.LOGIN_TOKEN_SECRET }}
          
          # Frontend Configuration
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          
          # Cache Storage
          REDIS_URL: ${{ secrets.REDIS_URL }}
          
          # Supabase Integration
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          
          # QStash for background jobs
          QSTASH_TOKEN: ${{ secrets.QSTASH_TOKEN }}
          QSTASH_CURRENT_SIGNING_KEY: ${{ secrets.QSTASH_CURRENT_SIGNING_KEY }}
          QSTASH_NEXT_SIGNING_KEY: ${{ secrets.QSTASH_NEXT_SIGNING_KEY }}
          
          # Google Calendar Integration
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          vercel-args: --prod